[package]
name = "libevent-sys"
version = "0.2.1"
authors = ["Steven vanZyl <rushsteve1@rushsteve1.us>"]
repository = "https://gitlab.com/tornado-torrent/libevent-sys"
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Rust FFI bindings to the libevent library" 
categories = ["external-ffi-bindings"]
keywords = ["ffi", "libevent", "event"]

links = "event"
build = "build.rs"

[badges]
gitlab = { repository = "tornado-torrent/libevent-sys", branch = "master" }

[features]
static = []

[build-dependencies]
bindgen = "^0.50"
pkg-config = "^0.3"
